// <auto-generated />
using System;
using Kurs.Rejestr;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace rejestr_rozpoznan.Migrations
{
    [DbContext(typeof(RegistersDbContext))]
    [Migration("20260831111802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Kurs.Rejestr.Diagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AgeOnset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodingSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfirmationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateDiagnosis")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOnset")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSymbolDiagnosis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalSystemKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icd10Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icd10Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("Kurs.Rejestr.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSymbolPatient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalSystemKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Kurs.Rejestr.Diagnosis", b =>
                {
                    b.HasOne("Kurs.Rejestr.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
